### ISSUE TITLE
Segmentation fault while running after successful build

### ISSUE THREAD

**Issue by yfoo** [TACC/core_usage#2]
Hi,

I'm trying to evaluate the core_usage program. The source compiles successfully, yet upon attempting to run after I see:

[ddd@wind /scratch/ddd/core_usage ]$ ./core_usage txt
To run the console version after one second.
Segmentation fault

[ddd@wind /scratch/ddd/core_usage ]$ gdb ./core_usage
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /scratch/ddd/core_usage/core_usage...(no debugging symbols found)...done.
(gdb) run
Starting program: /scratch/ddd/core_usage/core_usage 

Program received signal SIGSEGV, Segmentation fault.
0x0000000000403b13 in main ()

This is on a CentOS 6.10 system and gcc 6.2.0.

Thoughts? Thanks.

Best,
Chris

**Comment by wiliamhuang** [comment]
Hi Chris, 

  Thank you very much for reporting the issue. It was a bug introduced recently by adding new features. I just fixed it. Please try my latest code. Thank you for your interest in trying core_usage. 

Best Regards, 
-lei
